/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import static javax.swing.ScrollPaneConstants.*;

/**
 *
 * @author Arnau Comellas
 */
public class JFrameHorari extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHorari
     */
    private CtrlPresentacio cP;
    public JFrameHorari(CtrlPresentacio c) {
        cP = c;
        this.setUndecorated(true);
        initComponents();
        //cP.prova = cP.printHorari();
        Bonic1();
        
        //Omplir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dilluns_8 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dimarts_8 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Dimecres_8 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Dijous_8 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Divendres_8 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        Dilluns_9 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        Dimarts_9 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Dimecres_9 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        Dijous_9 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        Divendres_9 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        Dilluns_10 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        Dimarts_10 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        Dimecres_10 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        Dijous_10 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        Divendres_10 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        Dilluns_11 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        Dimarts_11 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        Dimecres_11 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        Dijous_11 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        Divendres_11 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        Dilluns_12 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        Dimarts_12 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        Dimecres_12 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        Dijous_12 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        Divendres_12 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        Dilluns_13 = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        Dimarts_13 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        Dimecres_13 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        Dijous_13 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        Divendres_13 = new javax.swing.JTextArea();
        jScrollPane31 = new javax.swing.JScrollPane();
        Dilluns_14 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        Dimarts_14 = new javax.swing.JTextArea();
        jScrollPane33 = new javax.swing.JScrollPane();
        Dimecres_14 = new javax.swing.JTextArea();
        jScrollPane34 = new javax.swing.JScrollPane();
        Dijous_14 = new javax.swing.JTextArea();
        jScrollPane35 = new javax.swing.JScrollPane();
        Divendres_14 = new javax.swing.JTextArea();
        jScrollPane36 = new javax.swing.JScrollPane();
        Dilluns_15 = new javax.swing.JTextArea();
        jScrollPane37 = new javax.swing.JScrollPane();
        Dilluns_16 = new javax.swing.JTextArea();
        jScrollPane38 = new javax.swing.JScrollPane();
        Dilluns_17 = new javax.swing.JTextArea();
        jScrollPane39 = new javax.swing.JScrollPane();
        Dilluns_18 = new javax.swing.JTextArea();
        jScrollPane40 = new javax.swing.JScrollPane();
        Dilluns_19 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane41 = new javax.swing.JScrollPane();
        Dimarts_15 = new javax.swing.JTextArea();
        jScrollPane42 = new javax.swing.JScrollPane();
        Dimecres_15 = new javax.swing.JTextArea();
        jScrollPane43 = new javax.swing.JScrollPane();
        Dijous_15 = new javax.swing.JTextArea();
        jScrollPane44 = new javax.swing.JScrollPane();
        Divendres_15 = new javax.swing.JTextArea();
        jScrollPane45 = new javax.swing.JScrollPane();
        Dimarts_16 = new javax.swing.JTextArea();
        jScrollPane46 = new javax.swing.JScrollPane();
        Dimecres_16 = new javax.swing.JTextArea();
        jScrollPane47 = new javax.swing.JScrollPane();
        Dijous_16 = new javax.swing.JTextArea();
        jScrollPane48 = new javax.swing.JScrollPane();
        Divendres_16 = new javax.swing.JTextArea();
        jScrollPane49 = new javax.swing.JScrollPane();
        Dimarts_17 = new javax.swing.JTextArea();
        jScrollPane50 = new javax.swing.JScrollPane();
        Dimecres_17 = new javax.swing.JTextArea();
        jScrollPane51 = new javax.swing.JScrollPane();
        Dijous_17 = new javax.swing.JTextArea();
        jScrollPane52 = new javax.swing.JScrollPane();
        Divendres_17 = new javax.swing.JTextArea();
        jScrollPane53 = new javax.swing.JScrollPane();
        Dimarts_18 = new javax.swing.JTextArea();
        jScrollPane54 = new javax.swing.JScrollPane();
        Dimecres_18 = new javax.swing.JTextArea();
        jScrollPane55 = new javax.swing.JScrollPane();
        Dijous_18 = new javax.swing.JTextArea();
        jScrollPane56 = new javax.swing.JScrollPane();
        Divendres_18 = new javax.swing.JTextArea();
        jScrollPane57 = new javax.swing.JScrollPane();
        Dimarts_19 = new javax.swing.JTextArea();
        jScrollPane58 = new javax.swing.JScrollPane();
        Dimecres_19 = new javax.swing.JTextArea();
        jScrollPane59 = new javax.swing.JScrollPane();
        Dijous_19 = new javax.swing.JTextArea();
        jScrollPane60 = new javax.swing.JScrollPane();
        Divendres_19 = new javax.swing.JTextArea();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField1.setText("Hora/Dia");
        jTextField1.setPreferredSize(new java.awt.Dimension(120, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField2.setText("Dilluns");
        jTextField2.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField3.setText("Dimarts");
        jTextField3.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField4.setText("Dimecres");
        jTextField4.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField5.setText("Dijous");
        jTextField5.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField6.setText("Divendres");
        jTextField6.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField7.setText("8:00 - 9:00");
        jTextField7.setPreferredSize(new java.awt.Dimension(120, 25));

        Dilluns_8.setEditable(false);
        Dilluns_8.setColumns(20);
        Dilluns_8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_8.setRows(5);
        Dilluns_8.setToolTipText("");
        jScrollPane1.setViewportView(Dilluns_8);

        Dimarts_8.setEditable(false);
        Dimarts_8.setColumns(20);
        Dimarts_8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_8.setRows(5);
        Dimarts_8.setToolTipText("");
        jScrollPane2.setViewportView(Dimarts_8);

        Dimecres_8.setEditable(false);
        Dimecres_8.setColumns(20);
        Dimecres_8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_8.setRows(5);
        Dimecres_8.setToolTipText("");
        jScrollPane3.setViewportView(Dimecres_8);

        Dijous_8.setEditable(false);
        Dijous_8.setColumns(20);
        Dijous_8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_8.setRows(5);
        Dijous_8.setToolTipText("");
        jScrollPane4.setViewportView(Dijous_8);

        Divendres_8.setEditable(false);
        Divendres_8.setColumns(20);
        Divendres_8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_8.setRows(5);
        Divendres_8.setToolTipText("");
        jScrollPane5.setViewportView(Divendres_8);

        Dilluns_9.setEditable(false);
        Dilluns_9.setColumns(20);
        Dilluns_9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_9.setRows(5);
        Dilluns_9.setToolTipText("");
        jScrollPane6.setViewportView(Dilluns_9);

        Dimarts_9.setEditable(false);
        Dimarts_9.setColumns(20);
        Dimarts_9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_9.setRows(5);
        Dimarts_9.setToolTipText("");
        jScrollPane7.setViewportView(Dimarts_9);

        jScrollPane8.setToolTipText("");

        Dimecres_9.setEditable(false);
        Dimecres_9.setColumns(20);
        Dimecres_9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_9.setRows(5);
        jScrollPane8.setViewportView(Dimecres_9);

        Dijous_9.setEditable(false);
        Dijous_9.setColumns(20);
        Dijous_9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_9.setRows(5);
        Dijous_9.setToolTipText("");
        jScrollPane9.setViewportView(Dijous_9);

        Divendres_9.setEditable(false);
        Divendres_9.setColumns(20);
        Divendres_9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_9.setRows(5);
        Divendres_9.setToolTipText("");
        jScrollPane10.setViewportView(Divendres_9);

        Dilluns_10.setEditable(false);
        Dilluns_10.setColumns(20);
        Dilluns_10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_10.setRows(5);
        Dilluns_10.setToolTipText("");
        jScrollPane11.setViewportView(Dilluns_10);

        Dimarts_10.setEditable(false);
        Dimarts_10.setColumns(20);
        Dimarts_10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_10.setRows(5);
        Dimarts_10.setToolTipText("");
        jScrollPane12.setViewportView(Dimarts_10);

        Dimecres_10.setEditable(false);
        Dimecres_10.setColumns(20);
        Dimecres_10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_10.setRows(5);
        Dimecres_10.setToolTipText("");
        jScrollPane13.setViewportView(Dimecres_10);

        Dijous_10.setEditable(false);
        Dijous_10.setColumns(20);
        Dijous_10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_10.setRows(5);
        Dijous_10.setToolTipText("");
        jScrollPane14.setViewportView(Dijous_10);

        Divendres_10.setEditable(false);
        Divendres_10.setColumns(20);
        Divendres_10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_10.setRows(5);
        Divendres_10.setToolTipText("");
        jScrollPane15.setViewportView(Divendres_10);

        Dilluns_11.setEditable(false);
        Dilluns_11.setColumns(20);
        Dilluns_11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_11.setRows(5);
        Dilluns_11.setToolTipText("");
        jScrollPane16.setViewportView(Dilluns_11);

        jScrollPane17.setToolTipText("");

        Dimarts_11.setEditable(false);
        Dimarts_11.setColumns(20);
        Dimarts_11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_11.setRows(5);
        jScrollPane17.setViewportView(Dimarts_11);

        Dimecres_11.setEditable(false);
        Dimecres_11.setColumns(20);
        Dimecres_11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_11.setRows(5);
        Dimecres_11.setToolTipText("");
        jScrollPane18.setViewportView(Dimecres_11);

        Dijous_11.setEditable(false);
        Dijous_11.setColumns(20);
        Dijous_11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_11.setRows(5);
        Dijous_11.setToolTipText("");
        jScrollPane19.setViewportView(Dijous_11);

        Divendres_11.setEditable(false);
        Divendres_11.setColumns(20);
        Divendres_11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_11.setRows(5);
        Divendres_11.setToolTipText("");
        jScrollPane20.setViewportView(Divendres_11);

        Dilluns_12.setEditable(false);
        Dilluns_12.setColumns(20);
        Dilluns_12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_12.setRows(5);
        Dilluns_12.setToolTipText("");
        jScrollPane21.setViewportView(Dilluns_12);

        Dimarts_12.setEditable(false);
        Dimarts_12.setColumns(20);
        Dimarts_12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_12.setRows(5);
        Dimarts_12.setToolTipText("");
        jScrollPane22.setViewportView(Dimarts_12);

        Dimecres_12.setEditable(false);
        Dimecres_12.setColumns(20);
        Dimecres_12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_12.setRows(5);
        Dimecres_12.setToolTipText("");
        jScrollPane23.setViewportView(Dimecres_12);

        Dijous_12.setEditable(false);
        Dijous_12.setColumns(20);
        Dijous_12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_12.setRows(5);
        Dijous_12.setToolTipText("");
        jScrollPane24.setViewportView(Dijous_12);

        Divendres_12.setEditable(false);
        Divendres_12.setColumns(20);
        Divendres_12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_12.setRows(5);
        Divendres_12.setToolTipText("");
        jScrollPane25.setViewportView(Divendres_12);

        Dilluns_13.setEditable(false);
        Dilluns_13.setColumns(20);
        Dilluns_13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_13.setRows(5);
        Dilluns_13.setToolTipText("");
        jScrollPane26.setViewportView(Dilluns_13);

        Dimarts_13.setEditable(false);
        Dimarts_13.setColumns(20);
        Dimarts_13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_13.setRows(5);
        Dimarts_13.setToolTipText("");
        jScrollPane27.setViewportView(Dimarts_13);

        Dimecres_13.setEditable(false);
        Dimecres_13.setColumns(20);
        Dimecres_13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_13.setRows(5);
        Dimecres_13.setToolTipText("");
        jScrollPane28.setViewportView(Dimecres_13);

        Dijous_13.setEditable(false);
        Dijous_13.setColumns(20);
        Dijous_13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_13.setRows(5);
        Dijous_13.setToolTipText("");
        jScrollPane29.setViewportView(Dijous_13);

        Divendres_13.setEditable(false);
        Divendres_13.setColumns(20);
        Divendres_13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_13.setRows(5);
        Divendres_13.setToolTipText("");
        jScrollPane30.setViewportView(Divendres_13);

        Dilluns_14.setEditable(false);
        Dilluns_14.setColumns(20);
        Dilluns_14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_14.setRows(5);
        Dilluns_14.setToolTipText("");
        jScrollPane31.setViewportView(Dilluns_14);

        Dimarts_14.setEditable(false);
        Dimarts_14.setColumns(20);
        Dimarts_14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_14.setRows(5);
        Dimarts_14.setToolTipText("");
        jScrollPane32.setViewportView(Dimarts_14);

        Dimecres_14.setEditable(false);
        Dimecres_14.setColumns(20);
        Dimecres_14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_14.setRows(5);
        Dimecres_14.setToolTipText("");
        jScrollPane33.setViewportView(Dimecres_14);

        Dijous_14.setEditable(false);
        Dijous_14.setColumns(20);
        Dijous_14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_14.setRows(5);
        Dijous_14.setToolTipText("");
        jScrollPane34.setViewportView(Dijous_14);

        Divendres_14.setEditable(false);
        Divendres_14.setColumns(20);
        Divendres_14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_14.setRows(5);
        Divendres_14.setToolTipText("");
        jScrollPane35.setViewportView(Divendres_14);

        Dilluns_15.setEditable(false);
        Dilluns_15.setColumns(20);
        Dilluns_15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_15.setRows(5);
        Dilluns_15.setToolTipText("");
        jScrollPane36.setViewportView(Dilluns_15);

        Dilluns_16.setEditable(false);
        Dilluns_16.setColumns(20);
        Dilluns_16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_16.setRows(5);
        Dilluns_16.setToolTipText("");
        jScrollPane37.setViewportView(Dilluns_16);

        Dilluns_17.setEditable(false);
        Dilluns_17.setColumns(20);
        Dilluns_17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_17.setRows(5);
        Dilluns_17.setToolTipText("");
        jScrollPane38.setViewportView(Dilluns_17);

        Dilluns_18.setEditable(false);
        Dilluns_18.setColumns(20);
        Dilluns_18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_18.setRows(5);
        Dilluns_18.setToolTipText("");
        jScrollPane39.setViewportView(Dilluns_18);

        Dilluns_19.setEditable(false);
        Dilluns_19.setColumns(20);
        Dilluns_19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dilluns_19.setRows(5);
        Dilluns_19.setToolTipText("");
        jScrollPane40.setViewportView(Dilluns_19);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setText("Enrere");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Dimarts_15.setEditable(false);
        Dimarts_15.setColumns(20);
        Dimarts_15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_15.setRows(5);
        Dimarts_15.setToolTipText("");
        jScrollPane41.setViewportView(Dimarts_15);

        Dimecres_15.setEditable(false);
        Dimecres_15.setColumns(20);
        Dimecres_15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_15.setRows(5);
        Dimecres_15.setToolTipText("");
        jScrollPane42.setViewportView(Dimecres_15);

        Dijous_15.setEditable(false);
        Dijous_15.setColumns(20);
        Dijous_15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_15.setRows(5);
        Dijous_15.setToolTipText("");
        jScrollPane43.setViewportView(Dijous_15);

        Divendres_15.setEditable(false);
        Divendres_15.setColumns(20);
        Divendres_15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_15.setRows(5);
        Divendres_15.setToolTipText("");
        jScrollPane44.setViewportView(Divendres_15);

        Dimarts_16.setEditable(false);
        Dimarts_16.setColumns(20);
        Dimarts_16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_16.setRows(5);
        Dimarts_16.setToolTipText("");
        jScrollPane45.setViewportView(Dimarts_16);

        Dimecres_16.setEditable(false);
        Dimecres_16.setColumns(20);
        Dimecres_16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_16.setRows(5);
        Dimecres_16.setToolTipText("");
        jScrollPane46.setViewportView(Dimecres_16);

        Dijous_16.setEditable(false);
        Dijous_16.setColumns(20);
        Dijous_16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_16.setRows(5);
        Dijous_16.setToolTipText("");
        jScrollPane47.setViewportView(Dijous_16);

        Divendres_16.setEditable(false);
        Divendres_16.setColumns(20);
        Divendres_16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_16.setRows(5);
        Divendres_16.setToolTipText("");
        jScrollPane48.setViewportView(Divendres_16);

        Dimarts_17.setEditable(false);
        Dimarts_17.setColumns(20);
        Dimarts_17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_17.setRows(5);
        Dimarts_17.setToolTipText("");
        jScrollPane49.setViewportView(Dimarts_17);

        Dimecres_17.setEditable(false);
        Dimecres_17.setColumns(20);
        Dimecres_17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_17.setRows(5);
        Dimecres_17.setToolTipText("");
        jScrollPane50.setViewportView(Dimecres_17);

        Dijous_17.setEditable(false);
        Dijous_17.setColumns(20);
        Dijous_17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_17.setRows(5);
        Dijous_17.setToolTipText("");
        jScrollPane51.setViewportView(Dijous_17);

        Divendres_17.setEditable(false);
        Divendres_17.setColumns(20);
        Divendres_17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_17.setRows(5);
        Divendres_17.setToolTipText("");
        jScrollPane52.setViewportView(Divendres_17);

        Dimarts_18.setEditable(false);
        Dimarts_18.setColumns(20);
        Dimarts_18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_18.setRows(5);
        Dimarts_18.setToolTipText("");
        jScrollPane53.setViewportView(Dimarts_18);

        jScrollPane54.setToolTipText("");

        Dimecres_18.setEditable(false);
        Dimecres_18.setColumns(20);
        Dimecres_18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_18.setRows(5);
        jScrollPane54.setViewportView(Dimecres_18);

        Dijous_18.setEditable(false);
        Dijous_18.setColumns(20);
        Dijous_18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_18.setRows(5);
        Dijous_18.setToolTipText("");
        jScrollPane55.setViewportView(Dijous_18);

        Divendres_18.setEditable(false);
        Divendres_18.setColumns(20);
        Divendres_18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_18.setRows(5);
        Divendres_18.setToolTipText("");
        jScrollPane56.setViewportView(Divendres_18);

        Dimarts_19.setEditable(false);
        Dimarts_19.setColumns(20);
        Dimarts_19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimarts_19.setRows(5);
        Dimarts_19.setToolTipText("");
        jScrollPane57.setViewportView(Dimarts_19);

        Dimecres_19.setEditable(false);
        Dimecres_19.setColumns(20);
        Dimecres_19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dimecres_19.setRows(5);
        Dimecres_19.setToolTipText("");
        jScrollPane58.setViewportView(Dimecres_19);

        Dijous_19.setEditable(false);
        Dijous_19.setColumns(20);
        Dijous_19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dijous_19.setRows(5);
        Dijous_19.setToolTipText("");
        jScrollPane59.setViewportView(Dijous_19);

        Divendres_19.setEditable(false);
        Divendres_19.setColumns(20);
        Divendres_19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Divendres_19.setRows(5);
        Divendres_19.setToolTipText("");
        jScrollPane60.setViewportView(Divendres_19);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField8.setText("9:00 - 10:00");
        jTextField8.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField9.setText("10:00 - 11:00");
        jTextField9.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField10.setText("11:00 - 12:00");
        jTextField10.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField11.setText("12:00 - 13:00");
        jTextField11.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField12.setText("13:00 - 14:00");
        jTextField12.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField13.setText("14:00 - 15:00");
        jTextField13.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField14.setText("15:00 - 16:00");
        jTextField14.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField15.setEditable(false);
        jTextField15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField15.setText("16:00 - 17:00");
        jTextField15.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField16.setEditable(false);
        jTextField16.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField16.setText("17:00 - 18:00");
        jTextField16.setPreferredSize(new java.awt.Dimension(120, 25));

        jTextField17.setEditable(false);
        jTextField17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField17.setText("18:00 - 19:00");
        jTextField17.setPreferredSize(new java.awt.Dimension(120, 25));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        jTextField18.setEditable(false);
        jTextField18.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField18.setText("19:00 - 20:00");
        jTextField18.setPreferredSize(new java.awt.Dimension(120, 25));
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane53, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane57, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane54, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane58, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane55, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane56, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane52, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane48, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.dispose();
        cP.carregaHorari();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.dispose();
        cP.ModificarHorari();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    private void Omplir() {
        List<JTextArea> Dilluns = new ArrayList<>(Arrays.asList(Dilluns_8, Dilluns_9, Dilluns_10, Dilluns_11, Dilluns_12, Dilluns_13, Dilluns_14, Dilluns_15, Dilluns_16, Dilluns_17, Dilluns_18, Dilluns_19));
        List<JTextArea> Dimarts = new ArrayList<>(Arrays.asList( Dimarts_8, Dimarts_9, Dimarts_10, Dimarts_11, Dimarts_12, Dimarts_13, Dimarts_14, Dimarts_15, Dimarts_16, Dimarts_17, Dimarts_18, Dimarts_19));
        List<JTextArea> Dimecres = new ArrayList<>(Arrays.asList(Dimecres_8, Dimecres_9, Dimecres_10, Dimecres_11, Dimecres_12, Dimecres_13, Dimecres_14, Dimecres_15, Dimecres_16, Dimecres_17, Dimecres_18, Dimecres_19));
        List<JTextArea> Dijous = new ArrayList<>(Arrays.asList(Dijous_8, Dijous_9, Dijous_10, Dijous_11, Dijous_12, Dijous_13, Dijous_14, Dijous_15, Dijous_16, Dijous_17, Dijous_18, Dijous_19));
        List<JTextArea> Divendres = new ArrayList<>(Arrays.asList(Divendres_8, Divendres_9, Divendres_10, Divendres_11, Divendres_12, Divendres_13, Divendres_14, Divendres_15, Divendres_16, Divendres_17, Divendres_18, Divendres_19));
        
        for(int i = 0; i < Dilluns.size();i++){
            Dilluns.get(i).append(cP.prova[0][i]);
        }
        for(int i = 0; i < Dimarts.size();i++){
            Dimarts.get(i).append(cP.prova[1][i]);
        }
        for(int i = 0; i < Dimecres.size();i++){
            Dimecres.get(i).append(cP.prova[2][i]);
        }
        for(int i = 0; i < Dijous.size();i++){
            Dijous.get(i).append(cP.prova[3][i]);
        }
        for(int i = 0; i < Divendres.size();i++){
            Divendres.get(i).append(cP.prova[4][i]);
        }
    }
    private void Bonic1() {
        List<JScrollPane> jScrollPaneList = new ArrayList<>(Arrays.asList(jScrollPane1,jScrollPane2,jScrollPane3,jScrollPane4,jScrollPane5,jScrollPane6,jScrollPane7,jScrollPane8,jScrollPane9,jScrollPane10,jScrollPane11,jScrollPane12,jScrollPane13,jScrollPane14,jScrollPane15,jScrollPane16,jScrollPane17,jScrollPane18,jScrollPane19,jScrollPane20,jScrollPane21,jScrollPane22,jScrollPane23,jScrollPane24,jScrollPane25,jScrollPane26,jScrollPane27,jScrollPane28,jScrollPane29,jScrollPane30,jScrollPane31,jScrollPane32,jScrollPane33,jScrollPane34,jScrollPane35,jScrollPane36,jScrollPane37,jScrollPane38,jScrollPane39,jScrollPane40,jScrollPane41,jScrollPane42,jScrollPane43,jScrollPane44,jScrollPane45,jScrollPane46,jScrollPane47,jScrollPane48,jScrollPane49,jScrollPane50,jScrollPane51,jScrollPane52,jScrollPane53,jScrollPane54,jScrollPane55,jScrollPane56,jScrollPane57,jScrollPane58,jScrollPane59,jScrollPane60));
        for(int i = 0; i < jScrollPaneList.size();i++){
        jScrollPaneList.get(i).setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
    }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Dijous_10;
    private javax.swing.JTextArea Dijous_11;
    private javax.swing.JTextArea Dijous_12;
    private javax.swing.JTextArea Dijous_13;
    private javax.swing.JTextArea Dijous_14;
    private javax.swing.JTextArea Dijous_15;
    private javax.swing.JTextArea Dijous_16;
    private javax.swing.JTextArea Dijous_17;
    private javax.swing.JTextArea Dijous_18;
    private javax.swing.JTextArea Dijous_19;
    private javax.swing.JTextArea Dijous_8;
    private javax.swing.JTextArea Dijous_9;
    private javax.swing.JTextArea Dilluns_10;
    private javax.swing.JTextArea Dilluns_11;
    private javax.swing.JTextArea Dilluns_12;
    private javax.swing.JTextArea Dilluns_13;
    private javax.swing.JTextArea Dilluns_14;
    private javax.swing.JTextArea Dilluns_15;
    private javax.swing.JTextArea Dilluns_16;
    private javax.swing.JTextArea Dilluns_17;
    private javax.swing.JTextArea Dilluns_18;
    private javax.swing.JTextArea Dilluns_19;
    private javax.swing.JTextArea Dilluns_8;
    private javax.swing.JTextArea Dilluns_9;
    private javax.swing.JTextArea Dimarts_10;
    private javax.swing.JTextArea Dimarts_11;
    private javax.swing.JTextArea Dimarts_12;
    private javax.swing.JTextArea Dimarts_13;
    private javax.swing.JTextArea Dimarts_14;
    private javax.swing.JTextArea Dimarts_15;
    private javax.swing.JTextArea Dimarts_16;
    private javax.swing.JTextArea Dimarts_17;
    private javax.swing.JTextArea Dimarts_18;
    private javax.swing.JTextArea Dimarts_19;
    private javax.swing.JTextArea Dimarts_8;
    private javax.swing.JTextArea Dimarts_9;
    private javax.swing.JTextArea Dimecres_10;
    private javax.swing.JTextArea Dimecres_11;
    private javax.swing.JTextArea Dimecres_12;
    private javax.swing.JTextArea Dimecres_13;
    private javax.swing.JTextArea Dimecres_14;
    private javax.swing.JTextArea Dimecres_15;
    private javax.swing.JTextArea Dimecres_16;
    private javax.swing.JTextArea Dimecres_17;
    private javax.swing.JTextArea Dimecres_18;
    private javax.swing.JTextArea Dimecres_19;
    private javax.swing.JTextArea Dimecres_8;
    private javax.swing.JTextArea Dimecres_9;
    private javax.swing.JTextArea Divendres_10;
    private javax.swing.JTextArea Divendres_11;
    private javax.swing.JTextArea Divendres_12;
    private javax.swing.JTextArea Divendres_13;
    private javax.swing.JTextArea Divendres_14;
    private javax.swing.JTextArea Divendres_15;
    private javax.swing.JTextArea Divendres_16;
    private javax.swing.JTextArea Divendres_17;
    private javax.swing.JTextArea Divendres_18;
    private javax.swing.JTextArea Divendres_19;
    private javax.swing.JTextArea Divendres_8;
    private javax.swing.JTextArea Divendres_9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JScrollPane jScrollPane53;
    private javax.swing.JScrollPane jScrollPane54;
    private javax.swing.JScrollPane jScrollPane55;
    private javax.swing.JScrollPane jScrollPane56;
    private javax.swing.JScrollPane jScrollPane57;
    private javax.swing.JScrollPane jScrollPane58;
    private javax.swing.JScrollPane jScrollPane59;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane60;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    public void run() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
}
